### ISSUE TITLE
Add destroy method

### ISSUE THREAD

**Issue by thasmo** [peduarte/wallop#62]
#25 mentions adding a `destroy` method. As I haven't found a ` destroy` method in the codebase, I propose to add one, because it's a very useful feature when implementing Wallop in RWD projects.

**Comment by peduarte** [comment]
Merged, thanks!

**Comment by magicspon** [comment]
Hello,

Has a destory method been added? I can't see it in the source code.

Cheers

**Comment by peduarte** [comment]
hello, wallop has `reset()` method  now which should be helpful when adding/removing items dynamically. Otherwise, CSS Media queries should be enough to turn the Slider into a Stacked list of items on mobile view.

**Comment by essmahr** [comment]
Hi! I'd like to revisit this if possible. I think a destroy method would be beneficial, here's my use case:

I'm using wallop in a situation the entire domNode is being replaced via ajax. I can't `reset()` because all original bindings have been wiped out, even though the new markup is identical. And with the current approach, I can't reinstantiate, because wallop is caching the current selector and so it throws the `'An instance of Wallop with this selector already exists.'` error.

I'd like to explore either a `destroy()` method, or a change in the behaviour so that existing instances can be re-instantiated.

Thanks for a very logical, flexible library :)

**Comment by honzabilek4** [comment]
Hi,
I'd just like to say that this is closely related to issue #75.
