### ISSUE TITLE
Auto Start

### ISSUE THREAD

**Issue by pvernaglia** [peduarte/wallop#63]
Hi, Can you give an example of how to have wallop auto start and loop through the slides?  this is what carousel is for?  thanks

**Comment by 19h47** [comment]
Hi pvernaglia, Wallop doesn't have option for auto start, because peduarte wants to keep Wallop as simple as possible.
Carousel option is to loop through item. When slide reaches the end, it continues with the first item.

Personally, I do it with GSAP and the next() and previous() control when the animation is complete.

**Comment by peduarte** [comment]
Hey @pvernaglia, what @19h47 said is spot on. I don't want to bloat this library with too many options, instead, I offer the tools you need to extend it to suit your use case.

I wrote a simple Auto Start example here: http://codepen.io/peduarte/pen/RapQBB

Hope it helps!

**Comment by danimalweb** [comment]
Thanks for the Autostart code, its really helpful. What's the best way to get it to loop?
